from apps.docs.decorators import (
    PARKING_LOT_VIEWSET_DOCS,
    PARKING_LOT_AVAILABILITY_DOCS,
    BOOKING_VIEWSET_DOCS,
    BOOKING_EXTEND_SESSION_DOCS,
    BOOKING_CANCEL_DOCS,
    MY_PARKING_LOTS_VIEWSET_DOCS,
    MY_PARKING_LOT_BOOKINGS_DOCS,
    SEARCH_PARKING_SPOTS_DOCS,
    DASHBOARD_STATS_DOCS
)

from apps.docs.decorators import (
    USER_VIEWSET_DOCS,
    USER_REGISTER_DOCS,
    USER_LOGIN_DOCS,
    USER_LOGOUT_DOCS,
    USER_PROFILE_DOCS,
    USER_CHANGE_PASSWORD_DOCS,
    USER_PROTECTED_DOCS
)