# Generated by Django 5.1.6 on 2025-04-04 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry",
            old_name="value",
            new_name="amount",
        ),
    ]
