# Generated by Django 5.1.6 on 2025-07-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_value_entry_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="currency",
            field=models.CharField(default="BRL", max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="currency_symbol",
            field=models.CharField(default="R$", max_length=3),
            preserve_default=False,
        ),
    ]
